### ISSUE TITLE
How to edit weather to generate different style video?

### ISSUE THREAD

**Issue by RobotiX101** [PJLab-ADG/DriveArena#10]

**Comment by zijinoier** [comment]
Please modify **both** two files to edit weather:
1. https://github.com/PJLab-ADG/DriveArena/blob/ba7dd86b606b92710e111e55fa639ebf6ebe0ed4/WorldDreamer/tools/dreamer_fast_api.py#L83
select one pre-defined style from the following: `boston`, `boston_sunny`,`singapore_rain`, `hollandvillage_night`
2. https://github.com/PJLab-ADG/DriveArena/blob/ba7dd86b606b92710e111e55fa639ebf6ebe0ed4/TrafficManager/config.yaml#L17
modify the `gen_description` that matches the above pre-defined style.

**Comment by RobotiX101** [comment]
Thanks
