### ISSUE TITLE
Not Found create_gt_database.py

### ISSUE THREAD

**Issue by yukiy927** [PJLab-ADG/DriveArena#11]
Hi there,

When I was trying to generate ann_file using the following command:

`python -m tools.create_data nuscenes \
--root-path /path/to/nuscenes --out-dir ./data/nuscenes_mmdet3d-t-keyframes/ \
--extra-tag nuscenes --only_info`

It returns as follows:
```
    from data_converter.create_gt_database import create_groundtruth_database
ModuleNotFoundError: No module named 'data_converter.create_gt_database'
```

I traced back the data_converter but I did not find the related definition about create_gt_database. Could you uploud any auxiliary files for reference?

**Comment by jokester-zzz** [comment]
We apologize for our negligence. we found that the pkl generated by this function is actually useless, so we did not provide this part of the code. We have modified the code and you can pull it again~

**Comment by zhoujiawei3** [comment]
Code may not change
