### ISSUE TITLE
how to locate the ego locations in the original nuscenes map?

### ISSUE THREAD

**Issue by yanty123** [PJLab-ADG/DriveArena#12]
Very amazing project!

Maybe there is some differences between the given "singapore-onenorth" and the original  nuscence "singapore-onenorth", for example , when i use the same ego pose to locate, i get different hd bev maps from your code and the original nuscenes map explorer.

**Comment by jokester-zzz** [comment]
Thanks for your attention to our project~
The maps we provide are sourced from OpenStreetMap rather than directly converted from the original nuscenes map. This can lead to discrepancies, so complete alignment with the original nuscenes map may not be possible. We appreciate your understanding.
