### ISSUE TITLE
about install mmcv-full

### ISSUE THREAD

**Issue by WuZhongQing** [PJLab-ADG/DriveArena#13]
i found its hard to install mmcv-full in my enviroment, so i want to ask if i can use mmcv-full==1.7.2 ? cause it can be installed without error.

**Comment by jokester-zzz** [comment]
I'm not sure if this version will conflict with other libraries, I suggest you verify it by running the test script after installing all environments: 
https://github.com/PJLab-ADG/DriveArena/blob/dcd90e8ee6c95de38865436a98184b4ce64bbe46/WorldDreamer/docs/GETTING_STARTED.md?plain=1#L193

**Comment by WuZhongQing** [comment]
> I'm not sure if this version will conflict with other libraries, I suggest you verify it by running the test script after installing all environments:
> 
> https://github.com/PJLab-ADG/DriveArena/blob/dcd90e8ee6c95de38865436a98184b4ce64bbe46/WorldDreamer/docs/GETTING_STARTED.md?plain=1#L193

thanks for your reply ~
