### ISSUE TITLE
 Video Autoregression Dreamer

### ISSUE THREAD

**Issue by DevinCheung** [PJLab-ADG/DriveArena#14]
Thanks for your awesome work! May I ask when the video-version world dreamer would be released? Thanks!

**Comment by DevinCheung** [comment]
And the pretrained model "SDv1.5_mv_single_ref_nus" is only for multi-view **_image_** generation, not multi-view **_video_** generation? Thanks!

**Comment by jokester-zzz** [comment]
Thank you for your recognition.

"SDv1.5_mv_single_ref_nus" is a single-frame implementation of the autoregressive generation algorithm, it does has limitations in preserving temporal consistency. We are actively working on a more continuous version and have already achieved some promising results. For more details, you can refer to our [report](https://arxiv.org/abs/2409.04003). We may also consider open-sourcing this part of the code in the future.
