### ISSUE TITLE
about how to improve the smoothness of generated video. 

### ISSUE THREAD

**Issue by WuZhongQing** [PJLab-ADG/DriveArena#15]
Hi, i have some confusion about how to improve the smoothness of generated video, cause i found that frames does't match the next frame, so i'm wondering is that any trick to improve that ?

https://github.com/user-attachments/assets/02e53def-e87b-47be-b18c-3d1db2c3a9c5

**Comment by WuZhongQing** [comment]
and another question is how to change the style of demo_data.pth, and i changed the images in the styles.py but it sames does't work.
![image](https://github.com/user-attachments/assets/ee946c68-40e7-4604-8dc8-fa045e1ca7ea)

and it generate the same style, so that i want to ask if there has something i need to change ?

**Comment by jokester-zzz** [comment]
The more continuous video version of the model is shown at the end of the [project page](https://pjlab-adg.github.io/DriveArena/). You can visit our [report](https://arxiv.org/abs/2409.04003) for more information. We may open source this part of the code later.

To change the generation style, you can also try changing the text prompt while changing the reference image.

**Comment by WuZhongQing** [comment]
> The more continuous video version of the model is shown at the end of the [project page](https://pjlab-adg.github.io/DriveArena/). You can visit our [report](https://arxiv.org/abs/2409.04003) for more information. We may open source this part of the code later.
> 
> To change the generation style, you can also try changing the text prompt while changing the reference image.

感谢您的回复，能问一下你们的“Video Autoregression Dreamer ”进展吗，我们领导想和贵实验室谈一下相关的合作，如果可以的话，可以加个微信聊聊吗？我的微信是qaq262032

**Comment by xiaodongww** [comment]
@WuZhongQing Hi, may i ask what version of sumo do you use? I just struggling with an error caused by sumo. the deail is described in this [issue](https://github.com/PJLab-ADG/DriveArena/issues/22#issue-2604659593). Any suggestion would be grateful. Thanks a lot.

**Comment by WuZhongQing** [comment]
> @WuZhongQing Hi, may i ask what version of sumo do you use? I just struggling with an error caused by sumo. the deail is described in this [issue](https://github.com/PJLab-ADG/DriveArena/issues/22#issue-2604659593). Any suggestion would be grateful. Thanks a lot.

i use the version of sumo recommened in requirements, and i dont run all the project, i just run the WorldDreamer
