### ISSUE TITLE
How to download  the descriptive data you generated using gpt-4v model?

### ISSUE THREAD

**Issue by Tony-Hou** [PJLab-ADG/DriveArena#16]
How to download  the descriptive data you generated using gpt-4v model?

**Comment by jokester-zzz** [comment]
We will upload the pkl files shortly and notify you in this issue. Please allow a few days for this. Thank you for your patience and understanding~

**Comment by xiaodongww** [comment]
Hi, thanks for your work.  Is that pkl file uploaded?  @jokester-zzz

**Comment by jokester-zzz** [comment]
Hi @xiaodongww, the `.pkl` files are uploaded, you can download from this [link](https://huggingface.co/datasets/jokester-yxm/DriveArena_data).😋
