### ISSUE TITLE
关于mmdet3d的安装问题

### ISSUE THREAD

**Issue by xuqiang656** [PJLab-ADG/DriveArena#19]
在运行python tools/test.py runner.validation_index=demo resume_from_checkpoint=path/to/your/weight   检测后，发现缺失mmdet3d文件，但requirements.txt中未包含该库，且由于mmcv-full和mmdet3d的兼容性问题，只能安装1.0.0rc0、0.18.0,、0.18.1三个版本，我尝试了很多安装方法（更换源，电脑等）都无法安装该库，会在build wheel时出错，所以想请问一下您这边有没有什么意见，或者编译好的wheel，感谢！
![8e2a0d0ff6c19469324fa2ee264fb82](https://github.com/user-attachments/assets/5fb4c141-71ad-4d2a-9650-880734bb3746) 
![mmdet3d](https://github.com/user-attachments/assets/6f621f7c-c59f-4e93-88ee-934de094336b)

**Comment by WuZhongQing** [comment]
> 在运行python tools/test.py runner.validation_index=demo resume_from_checkpoint=path/to/your/weight 检测后，发现缺失mmdet3d文件，但requirements.txt中未包含该库，且由于mmcv-full和mmdet3d的兼容性问题，只能安装1.0.0rc0、0.18.0,、0.18.1三个版本，我尝试了很多安装方法（更换源，电脑等）都无法安装该库，会在build wheel时出错，所以想请问一下您这边有没有什么意见，或者编译好的wheel，感谢！ ![8e2a0d0ff6c19469324fa2ee264fb82](https://private-user-images.githubusercontent.com/108315641/375949259-5fb4c141-71ad-4d2a-9650-880734bb3746.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTcyNjEsIm5iZiI6MTcyODk1Njk2MSwicGF0aCI6Ii8xMDgzMTU2NDEvMzc1OTQ5MjU5LTVmYjRjMTQxLTcxYWQtNGQyYS05NjUwLTg4MDczNGJiMzc0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwMTQ5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWY2ZTViZjQ0ZmYzNGZkODFjN2I5ZTQ4NWVjYjRmNmYyOWI1ZDFjMGRlNzEyMmQ1MzA1ZDA5YjM5NDg2YTQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XbFXQnT58jjUb75deZG0XusNBhFIetpecKZBoCKbCMA) ![mmdet3d](https://private-user-images.githubusercontent.com/108315641/375949118-6f621f7c-c59f-4e93-88ee-934de094336b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTcyNjEsIm5iZiI6MTcyODk1Njk2MSwicGF0aCI6Ii8xMDgzMTU2NDEvMzc1OTQ5MTE4LTZmNjIxZjdjLWM1OWYtNGU5My04OGVlLTkzNGRlMDk0MzM2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwMTQ5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzllNzdkOGJkN2U2NTYxYTQzYjgzY2QyOGI1NDdjNzA3ZDFmZGI4YzI3YzJkNjlkNTg5OWVjZDljN2FkZmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XyYW36SHeYyxAtndJs2VFN_UBZlvfjlh5UxeK_JSe4k)

你需要使用他代码里的三个第三方模块进行编译（如xformer,diffuser），然后再安装mmcv-full==1.4.5
