### ISSUE TITLE
When is the approximate time for the code to be open-sourced?

### ISSUE THREAD

**Issue by zxcasdzxcasdzxcasd** [PJLab-ADG/DriveArena#2]
Has the code already been open-sourced? Could you provide the complete code?

**Comment by jokester-zzz** [comment]
Thanks for your interest, the code is still being organized. We expect to have the code available by the end of September at the latest. If you would like to be notified when the code is released, you can fill out this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSe0j3b565JXab1dCZu0sBrXzJTajKB9rUfanyTzVBQoZcB9kg/viewform).
