### ISSUE TITLE
create_data.py are used to generate ann_file for nuscenes, but readme said it can also be used for nuplan

### ISSUE THREAD

**Issue by Sdty19** [PJLab-ADG/DriveArena#21]
Obviously create_data.py are not prepared for nuplan, and there is no nuplan.yaml in this project. 
![image](https://github.com/user-attachments/assets/1001be30-a004-43d2-93b8-43f71c0d57c2)

**Comment by tt-232** [comment]
Hi @Sdty19,

Thank you so much for using DriveArena! The current version of our WorldDreamer only supports the nuScenes dataset. The code for the nuPlan dataset will be released soon. I am sorry for the misunderstanding.

**Comment by tt-232** [comment]
Hi @Sdty19,

The code for processing the nuPlan dataset is now released. :)
