### ISSUE TITLE
Previous frame in the latent space

### ISSUE THREAD

**Issue by nkuwangfeng** [PJLab-ADG/DriveArena#24]
To complete video inference based on the first frame and make the generated situation more consistent with reality, simply adding the effect of the previous frame in the latent space is not very effective.

**Comment by jokester-zzz** [comment]
You are right. Indeed, our primary objective is to validate the feasibility of employing generative models as simulators. As for how to make the generator have better temporal consistency, we are also exploring it, and we expect growing interest from the research community in advancing the generator's capabilities.
