### ISSUE TITLE
About the worlddreamer agent render FPS

### ISSUE THREAD

**Issue by zzz5y** [PJLab-ADG/DriveArena#27]
Hello,thank you for your great work!
I wonder the FPS about the worlddreamer agent's render speed!
Thank you for your impressive work a lot!

**Comment by jokester-zzz** [comment]
The inference process requires approximately 20 seconds per frame with 50 sampling steps.

**Comment by zzz5y** [comment]
> The inference process requires approximately 20 seconds per frame with 50 sampling steps.

OK  thanks for you reply and your great work!
