### ISSUE TITLE
Temporal Consistency Issues in Video Generation: Strong Frame-to-Frame Variations in Both Background and Foreground

### ISSUE THREAD

**Issue by jiangchaokang** [PJLab-ADG/DriveArena#28]
I've been experimenting with your video generation framework and noticed some significant temporal consistency issues that I'd like to discuss:

### Current Issues Observed:
1. **Background Inconsistency**
   - Strong variations between consecutive frames
   - Lack of stable background elements despite reference image input

2. **Foreground Geometric Instability**
   - Significant geometric fluctuations in foreground objects
   - Poor frame-to-frame coherence in object shapes and positions

### Reference Comparison
I've noticed that works like DrivingDiffusion achieve much better temporal consistency in their demo results. Their framework maintains stable frame-to-frame transitions while preserving dynamic elements.

### Questions
1. Are there any strategies you're considering to improve temporal consistency in both background and foreground elements?
2. Could you share your thoughts on potential improvements to DriveArena's architecture to better handle frame coherence?
3. Have you considered incorporating temporal consistency constraints similar to those used in DrivingDiffusion?

Looking forward to your insights on addressing these stability challenges. Thank you for your time.

**Comment by jokester-zzz** [comment]
Thank you for your detailed observations and thoughtful questions regarding temporal consistency. You've raised some important points.

Our primary objective with this work was to validate the feasibility of utilizing generative models as simulators. While we acknowledge the current temporal consistency challenges you've identified, we believe these issues are surmountable and that there are already many researchers working on this problem. We're also actively developing a temporal version that has already shown promising results. The addition of temporal modules has indeed proven beneficial in our ongoing development.

As mentioned in our paper, one of the key advantages of our framework is that the World Dreamer component is designed to be modular and replaceable. We welcome the integration of more advanced algorithms to jointly promote the development of this project.

We appreciate your interest in advancing this technology and welcome the opportunity to discuss further developments in this space😉
