### ISSUE TITLE
Impressive work

### ISSUE THREAD

**Issue by sidiangongyuan** [PJLab-ADG/DriveArena#3]
This is an impressive piece of work! 
When can we expect the release of the development manual?
Additionally, does this platform support applications involving multi-vehicle collaboration （V2V or V2X）?

**Comment by jokester-zzz** [comment]
Thank you for your acknowledgement~
The manual is still under development. We expect to release it no later than October.
Currently, the platform does not support multi-vehicle collaboration, but we hope this feature will be available in the future. If you have good ideas, welcome to discuss and make pull requests!

**Comment by sidiangongyuan** [comment]
> Thank you for your acknowledgement~ The manual is still under development. We expect to release it no later than October. Currently, the platform does not support multi-vehicle collaboration, but we hope this feature will be available in the future. If you have good ideas, welcome to discuss and make pull requests!

OK,, ty ~
