### ISSUE TITLE
Train question

### ISSUE THREAD

**Issue by nkuwangfeng** [PJLab-ADG/DriveArena#32]
I saw in the paper that you trained 200k batches, does it have to be trained for such a long time to see the effect? I have trained 50K so far, and the result still looks very poor with an average loss of 0.12, which has not decreased for a long time. The effect of val is only visible in the outline, and the details are not very clear. I would like to ask if this is normal for you and if it is necessary to continue waiting?

**Comment by nkuwangfeng** [comment]
WorldDreamr

**Comment by zzz5y** [comment]
Hello may i ask you  what device are you using for training! I want to train my model too.

**Comment by nkuwangfeng** [comment]
> Hello may i ask you what device are you using for training! I want to train my model too.

A100 40G 8卡

**Comment by zzz5y** [comment]
> > Hello may i ask you what device are you using for training! I want to train my model too.
> 
> A100 40G 8卡

好的好的 谢谢！

**Comment by zzz5y** [comment]
Hello,May i ask you  how long do you need for training a iteration?

**Comment by jokester-zzz** [comment]
The complete training process of 200k steps took approximately 2-3 days. 

And after about 10k steps, we achieved the results shown in the figure.

![image](https://github.com/user-attachments/assets/c0b53e32-2dfb-4639-8e30-4a7366e26576)

**Comment by zzz5y** [comment]
> The complete training process of 200k steps took approximately 2-3 days.
> 
> And after about 10k steps, we achieved the results shown in the figure. (The image below is what we generated.)
> 
> ![image](https://private-user-images.githubusercontent.com/16915949/390383424-c0b53e32-2dfb-4639-8e30-4a7366e26576.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NjA1MDAsIm5iZiI6MTczMjc2MDIwMCwicGF0aCI6Ii8xNjkxNTk0OS8zOTAzODM0MjQtYzBiNTNlMzItMmRmYi00NjM5LThlMzAtNGE3MzY2ZTI2NTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDAyMTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMTZmZWJlNzUxYWI1Y2M5ZDNiYmMyZmU1MDRhMGUxNTU4MmYxYmNhYjZjYzBjNTFiMzFjNWUxYThhODRkZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6v7rsbFQmADazsFP9cfEVJs32y8sXrhjKNMr4HB8QAM)

OK, thanks you for reply!

**Comment by jokester-zzz** [comment]
I will close this issue. Please feel free to reopen it if you have any further questions or concerns~

**Comment by yzli-0910** [comment]
Hello @jokester-zzz, thank you for your amazing work!
I noticed you released DreamForge and DreamForge-DiT considering temporal consistency, and the training is splited into multiple stages.

I wonder if the training of these temporal models take much longer time in total?
If possible, could you please suggest how many hours would be needed for training on 8 A100s?
