### ISSUE TITLE
before testing ,Need prepare all data by following the steps in WorldDreamer?

### ISSUE THREAD

**Issue by zzz5y** [PJLab-ADG/DriveArena#33]
I want to test the WorldDreamer base on the pretrained sdf weights and dreamer weights and the demo data,but when i run
`python tools/test.py runner.validation_index=demo resume_from_checkpoint=./dreamer_pretrained/SDv1.5_mv_single_ref_nus/weight-S200000`
error happen,do you have any idea？
![image](https://github.com/user-attachments/assets/4fda994b-537e-42f4-b0c5-4fd31947c8af)
and then the program finish

**Comment by zzz5y** [comment]
I just prepare the worlddreamer day but without the description part

**Comment by jokester-zzz** [comment]
The description update issue alone should not trigger this type of error. Based on the screenshot provided, I am unable to determine the cause of the program termination. Could you please share additional configurations and relevant information to help diagnose the problem?

**Comment by zzz5y** [comment]
![image](https://github.com/user-attachments/assets/8f1c0541-1f26-419b-98d4-3e4583527923)
![image](https://github.com/user-attachments/assets/59dffdb4-a06b-4f12-be3c-dce601de90c1)
i add a printf in here
![image](https://github.com/user-attachments/assets/a3698a3c-743a-4097-80ed-5df788d6e19f)
it called in here
![image](https://github.com/user-attachments/assets/1fecf84b-3621-4965-b000-21d8d050bbf5)

**Comment by jokester-zzz** [comment]
To ensure compatibility with the nuPlan dataset, we check the data source from `filename` in this code section, but this does not affect the image generation pipeline. We recommend pulling the latest code base as we have fixed several bugs. It looks like you are currently running inference in demo mode, so `filename` is missing here, and your screenshots indicate that the image generation process seems functioning correctly. The generated images should be stored in the folder `DriveArena/WorldDreamer/dreamer-log/test/xxx`. Could you please check whether there are any images generated?

**Comment by zzz5y** [comment]
> To ensure compatibility with the nuPlan dataset, we check the data source from `filename` in this code section, but this does not affect the image generation pipeline. We recommend pulling the latest code base as we have fixed several bugs. It looks like you are currently running inference in demo mode, so `filename` is missing here, and your screenshots indicate that the image generation process seems functioning correctly. The generated images should be stored in the folder `DriveArena/WorldDreamer/dreamer-log/test/xxx`. Could you please check whether there are any images generated?

yes i found out the img there,does it work?But all img include in a folder, it's a little bit weird
![img_v3_02h2_78dc37c4-d121-4968-8592-e70e58a6747g](https://github.com/user-attachments/assets/e7d3f3d8-ea8d-485a-99be-98165a53506d)

**Comment by zzz5y** [comment]
> The images are indeed saved in one folder, and you can also modify the save path in [test.py](https://github.com/PJLab-ADG/DriveArena/blob/3fd2a319258b55ce8a7c7cc3fe2dcc89b61a1ff3/WorldDreamer/tools/test.py) yourself. 

Ok i got it ,thanks for you quick reply and your great work！
