### ISSUE TITLE
怎么在docker里面run起来呢

### ISSUE THREAD

**Issue by 2anchao** [PJLab-ADG/DriveArena#36]

**Comment by 2anchao** [comment]
运行python tools/dreamer_fast_api.py --resume=** 的时候发现浏览器找不到服务端口。构建容器的时候暴露了端口33/tcp, 0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 0.0.0.0:8060->22/tcp, :::8060->22/tcp。

**Comment by RealHaoyeChen** [comment]
请问每个模块单独一个docker 容器 还是所有的在一个容器里跑比较好
