### ISSUE TITLE
Performance Issues 

### ISSUE THREAD

**Issue by 0xTechSavvy** [PJLab-ADG/DriveArena#5]
Hello, this is a great project, and I really appreciate the open source. However, when I followed the instructions, the result wasn’t ideal. Could you please help me take a look at what might be the issue?

**Comment by hongdayu** [comment]
Uploading video.mp4…

**Comment by hongdayu** [comment]
![cat_053](https://github.com/user-attachments/assets/dd974fce-cbe7-4a17-8039-6813fe045422)
![cat_054](https://github.com/user-attachments/assets/eec38cc1-838b-48e0-baa0-d5e91ae42064)
![cat_055](https://github.com/user-attachments/assets/0261741a-f270-4c6e-9bd4-7a1838662be1)
![cat_056](https://github.com/user-attachments/assets/ba0ce8b5-6825-438b-87ea-5d0581c7382d)
![cat_057](https://github.com/user-attachments/assets/8be7e421-0999-4f30-a03a-376382827420)
![cat_058](https://github.com/user-attachments/assets/abfde558-21c1-4544-808d-79f494632144)
![cat_059](https://github.com/user-attachments/assets/6e336678-5c38-488a-90cc-a82c8b3989a3)
![cat_060](https://github.com/user-attachments/assets/239f764c-7753-4cd1-b478-22a3d571955a)
![cat_061](https://github.com/user-attachments/assets/bec2e112-b642-4229-b1ce-176de26739bb)
![cat_062](https://github.com/user-attachments/assets/94037439-6cdc-4842-9859-f68726ba0ef1)
![cat_063](https://github.com/user-attachments/assets/eea9dd76-d509-4488-9d72-029c283cbc24)
![cat_064](https://github.com/user-attachments/assets/628a3171-96e7-4352-a80f-b975185b4344)
![cat_065](https://github.com/user-attachments/assets/624381d0-54c4-440e-9836-e9d507db5242)

**Comment by zijinoier** [comment]
Thank you for your interest in our project and for trying it out. I'm glad to see you've successfully run the codebase.

Based on the image you provided, it appears that the images generated by WorldDreamer are functioning as intended.

However, I'm not clear on what you mean by "the result wasn't ideal." If you're referring to the erratic trajectory of the ego vehicle, I believe that you're running DriveArena in the `Closed-loop mode`. 
In this mode, the ego vehicle is entirely controlled by the DriverAgent (currently UniAD) in a closed-loop manner. As we mentioned in our paper, UniAD's closed-loop performance is not yet optimal, so **the ego vehicle behavior you're experiencing is actually expected** under these conditions.

**Comment by 0xTechSavvy** [comment]
> Thank you for your interest in our project and for trying it out. I'm glad to see you've successfully run the codebase.
> 
> Based on the image you provided, it appears that the images generated by WorldDreamer are functioning as intended.
> 
> However, I'm not clear on what you mean by "the result wasn't ideal." If you're referring to the erratic trajectory of the ego vehicle, I believe that you're running DriveArena in the `Closed-loop mode`. In this mode, the ego vehicle is entirely controlled by the DriverAgent (currently UniAD) in a closed-loop manner. As we mentioned in our paper, UniAD's closed-loop performance is not yet optimal, so **the ego vehicle behavior you're experiencing is actually expected** under these conditions.

Thank you for your reply. Yes, I am running in close-loop mode. What I mean by "the result wasn't ideal." is that when the ego car performs lane changes during maneuvering, the generated images change drastically, and the inconsistencies between consecutive frames are quite noticeable.

**Comment by jokester-zzz** [comment]
Since the current version is based on a single-frame autoregressive generator, it has certain shortcomings in terms of time consistency. (We are actively developing a more continuous version.)

As seen in the UniAD prediction results in the lower-right corner, the algorithm can correctly predict most of the vehicles and road structures, indicating that the scenes we generated can be understood by UniAD to a certain extent. 

It is indeed _difficult_ for us to determine whether it is a problem of the generator or the agent. In fact, the gap between simulation and reality is a question that most simulators have difficulty answering.
