### ISSUE TITLE
Hardware configuration

### ISSUE THREAD

**Issue by tianlangxingzz** [PJLab-ADG/DriveArena#6]
What if I just want to reproduce the inference process of your model and not train a GPU that requires much memory?

**Comment by zijinoier** [comment]
For inference only, a 4090-level GPU should be sufficient.

**Comment by tianlangxingzz** [comment]
Can a 4090 class GPU run your World Dreamer, UniAD and Traffic Manager in its entirety?

**Comment by zijinoier** [comment]
Yes, a RTX 4090 GPU would be efficient for running inference on both World Dreamer and UniAD.
Traffic Manager, doesn't require GPU resources and should be run on your local machine with a display.

**Comment by tianlangxingzz** [comment]
Okay, thank you very much for your reply.

**Comment by zzz5y** [comment]
> Yes, a RTX 4090 GPU would be efficient for running inference on both World Dreamer and UniAD.
> Traffic Manager, doesn't require GPU resources and should be run on your local machine with a display.

hello i wonder how much gpu memory need for training dreamer？
