### ISSUE TITLE
Generated images without movable objects

### ISSUE THREAD

**Issue by dyy0205** [PJLab-ADG/DriveArena#7]
Hi, great work for your job! 
Why are there no foreground objects such as cars in the pictures  I generated?
By the way,I have no openai account so i can't generate *updated_description_*.pkl file, so i just use original *12Hz_*.pkl as WorldDreamer's input, is that the reason?
<img width="879" alt="截屏2024-09-23 下午1 47 05" src="https://github.com/user-attachments/assets/93ac8dec-36bb-4734-9825-5ca9477170b9">

**Comment by jokester-zzz** [comment]
The visualization you show and the box projection at inference time are not executed at the same time. It is possible that the visualization is correct but the box is not actually projected onto the canvas.
Maybe you can check the code in the following function to see if it is executed correctly.
https://github.com/PJLab-ADG/DriveArena/blob/ba7dd86b606b92710e111e55fa639ebf6ebe0ed4/WorldDreamer/dataset/map_utils.py#L121

**Comment by dyy0205** [comment]
@jokester-zzz thank you very much! I have solved this problem. Due to mismatched opencv version, cv2.line may raise an tuple error, so by` try: except:` judgment, it may skip draw lines!

**Comment by jokester-zzz** [comment]
Congratulations on solving the problem! And it reminds me to add some instructions there😆

**Comment by xiaodongww** [comment]
@dyy0205 Hi, may i ask what version of sumo do you use? I just struggling with an error caused by sumo. the deail is described in this [issue](https://github.com/PJLab-ADG/DriveArena/issues/22#issue-2604659593). Any suggestion would be grateful. Thanks a lot.
