### ISSUE TITLE
ModuleNotFoundError: No module named 'xformers._flash_attn'

### ISSUE THREAD

**Issue by WuZhongQing** [PJLab-ADG/DriveArena#8]
hi, thanks for yuor open source ~, and this is a wondfoul work, when i prepared the data and try to run test , an error occured, like:
![image](https://github.com/user-attachments/assets/e838ce8b-cd56-4be1-9344-118816ce3806)

could you please help me debug this ~

**Comment by WuZhongQing** [comment]
i had debug that problem~

**Comment by jokester-zzz** [comment]
Congratulations! 🎉
If anyone encounters the same problem, please check this [issue](https://github.com/cure-lab/MagicDrive/issues/47) for a solution~

**Comment by RobotiX101** [comment]
To save ur time:
```
export XFORMERS_FORCE_DISABLE_TRITON=1 
```
