### ISSUE TITLE
about description.py for nuscenes 

### ISSUE THREAD

**Issue by WuZhongQing** [PJLab-ADG/DriveArena#9]
i found another error, it seams that the description.py in WorldDreamer just descript nuplane dataset , and could you please tell how to descript nuscenes, thanks a lot ~. 
and BWT  could you please provide the code to make demo.pth~

**Comment by zijinoier** [comment]
nuScenes  and nuPlan are using the same pipeline.  just modify these lines to read in nuscenes datasets:

https://github.com/PJLab-ADG/DriveArena/blob/ba7dd86b606b92710e111e55fa639ebf6ebe0ed4/WorldDreamer/tools/description.py#L87-L99

**Comment by WuZhongQing** [comment]
thanks for your reply , and i'm wondering that if you can provide the code to provide demo_data.pth ~
